// Types for adapt.mjs — learning from the people using it. Accepted and rejected suggestions are
// kept as a MEMORY applied to closely-worded input, not as a retrain of the head.

import type {
  Action, ClassifyDecision, Embedder, ReduceOptions, ShimReport, ShimWeightsInput, Vector,
} from './format.mjs';
import type { RecalibrateResult, Shim } from './index.mjs';

/** How close (cosine over the embedding, 0.82) an input must be to a remembered one to inherit its verdict. */
export const MEMORY_MATCH: number;

/** One remembered verdict. */
export interface FeedbackEntry {
  /** Generated by `record()`. */
  id: string;
  /** The input the verdict was about. */
  text: string;
  /** The answer the verdict is about. */
  label: string;
  /** `'yes'`: this answer is right for input like this. `'no'`: this answer is wrong for input like this. */
  verdict: 'yes' | 'no';
  /** The vector of `text`. Entries without one never match. */
  vector?: Vector | null;
  /** ISO 8601 timestamp, set by `record()`. */
  at: string;
  /** Free for the app to set (for instance, once a correction has been folded into the source). Not read by the SDK; survives `export()`. */
  committed?: boolean;
}

/** A feedback entry as `export()` writes it and `restore()` reads it: no vector. */
export type StoredFeedback = Omit<FeedbackEntry, 'vector'>;

/** The remembered input that matched. */
export interface MemoryMatch {
  text: string;
  /** Cosine to it, to three places. */
  similarity: number;
  /** The feedback entry's id. */
  id: string;
}

/**
 * A decision with memory applied. Exactly one of two shapes:
 * a remembered "yes" matched — `answer` is the remembered label, `action` is `'act'` and
 * `remembered` says why; or none did — `rejected` is set when a remembered "no" matched the base
 * answer (and `action` is then `'refuse'`), else `null`.
 * In both, `confidence`, `probs` and `familiarity` are the BASE shim's, about ITS answer.
 */
export type AdaptiveDecision = ClassifyDecision & {
  /** What the base shim said before memory was consulted. */
  shipped: { answer: string; confidence: number; action: Action };
  remembered?: MemoryMatch;
  rejected?: MemoryMatch | null;
};

/** A classify shim plus a memory of verdicts. Tags shims are not supported. */
export class AdaptiveShim {
  /**
   * Throws for a tags shim, and for anything `new Shim()` throws for.
   *
   * @param opts `match`: the cosine an input needs to a remembered one (default `MEMORY_MATCH`)
   */
  constructor(compiled: Shim | ShimWeightsInput, opts?: { match?: number });

  /** The underlying shim. */
  readonly base: Shim;
  match: number;
  readonly name: string;
  readonly labels: string[];
  readonly report: ShimReport;
  /** The memory, oldest first. */
  feedback: FeedbackEntry[];

  /** The closest remembered entry with this verdict (and label, when given), if it is within `match`; else `null`. */
  nearest(vec: Vector, verdict: 'yes' | 'no', label?: string | null): { entry: FeedbackEntry; similarity: number } | null;

  /** Decide from a vector, then let memory speak: a remembered "yes" replaces the answer, a remembered "no" for the base answer refuses. */
  decideVector(vec: Vector): AdaptiveDecision;

  /** Long input, with memory: each piece is decided by this shim, and the action follows the combined result unless memory spoke for the chosen piece. */
  decideChunks(vectors: readonly Vector[], chunks: readonly string[], opts?: ReduceOptions): AdaptiveDecision & { from: string; chunks: number };

  /** The base shim's `isConfident`. */
  isConfident(result: { confidence: number; familiarity?: number | null }, threshold?: number): boolean;

  /**
   * Record a decision with whatever is observing — what was SAID, tagged `via: 'adaptive'` with
   * `memory: 'yes' | 'no' | null`. Returns the result, with an `id` while something is observing.
   *
   * @param t0 `performance.now()` at the start of the call, for the row's `ms`
   * @param field the key this shim sits under in a bank
   */
  observed<R extends AdaptiveDecision>(r: R, text: string, vector: Vector | null, t0: number, field?: string | null): R;

  /**
   * Remember a verdict and return the entry. One verdict per (text, label); a new "yes" for a text
   * replaces any other "yes" for that same text.
   */
  record(entry: { text: string; vector?: Vector | null; label: string; verdict: 'yes' | 'no' }): FeedbackEntry;

  /** The base shim's calibration temperature. */
  get temperature(): number;

  /**
   * Refit the base shim's temperature on the remembered "yes" verdicts. These rows are not a random
   * sample — people correct what they were shown — so treat the result as better than the build's,
   * not as truth.
   */
  recalibrate(opts?: { minSamples?: number }): RecalibrateResult;

  /** Drop one entry by id. */
  forget(id: string): void;
  /** Drop every entry. */
  reset(): void;

  /** The memory in serialisable form: vectors dropped, to be recomputed from text on restore. */
  export(): StoredFeedback[];

  /**
   * REPLACE the memory with stored entries, re-embedding their texts in one call. Entries missing
   * `text`, `label` or `verdict` are dropped; when none are usable the memory is left as it was.
   *
   * @param embedder defaults to the embedder in play
   */
  restore(entries: readonly StoredFeedback[] | null | undefined, embedder?: Embedder): Promise<void>;
}

/** Several adaptive shims over one input, one encode. Each result carries the vector it was decided on, so a correction can be recorded against it. */
export class AdaptiveBank<S extends Record<string, AdaptiveShim | Shim | ShimWeightsInput> = Record<string, AdaptiveShim | Shim | ShimWeightsInput>> {
  /**
   * Unlike `Bank`, drafts are not skipped: a draft throws.
   *
   * @param opts passed to each `AdaptiveShim` this creates
   */
  constructor(shims: S, opts?: { match?: number });

  readonly shims: { [K in keyof S]: AdaptiveShim };

  /**
   * One encode, one decision per shim. Input over `LONG_INPUT_CHARS` is always split and reduced
   * by `'best'`; this takes no options. `vector` is the one decided on — for a long input, the chosen piece's.
   */
  decide(text: string): Promise<{ [K in keyof S]: AdaptiveDecision & { vector: Vector; id?: string; from?: string; chunks?: number } }>;
}
